async page => {
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 const check=(value,message)=>{if(!value)throw new Error(message);};
 await page.goto('http://localhost:5180/?demo=true');
 check(!await page.locator('#table-scope-field').isVisible(),'Table scope must be hidden initially');
 check(await page.locator('.summary-item.changed strong').innerText()==='3','Expected 3 changed tables');
 await page.locator('#mode').selectOption('names');
 check(await page.locator('.summary-item.changed strong').innerText()==='1','Names-only should exclude datatype/nullability changes');
 await page.locator('#mode').selectOption('types');
 check(await page.locator('.summary-item.changed strong').innerText()==='2','Type-only should compare matched columns');
 await page.locator('#scope').selectOption('selected');
 check(await page.locator('#table-scope-field').isVisible(),'Selected table control visible');
 check(await page.locator('.summary-item strong').first().innerText()==='1','Single-table scope');
 await page.locator('#target').selectOption('dev');
 check(await page.locator('.summary-item.same strong').innerText()==='1','Same database should match');
 await page.locator('#search-results').fill('no-match');
 check(await page.getByText('No matching objects. Try another filter or search.').isVisible(),'Empty search feedback');
 await page.getByRole('link',{name:'Data compare',exact:true}).click();
 check(await page.locator('.summary-item.changed strong').innerText()==='2','Expected 2 changed data rows');
 await page.locator('#ignore-city').check();
 check(await page.locator('.summary-item.changed strong').innerText()==='1','Ignore City should remove its difference');
 await page.locator('#match-key').selectOption('Email');
 check(await page.locator('.summary-item strong').first().innerText()==='8','Email key keeps 8 union rows');
 await page.getByRole('link',{name:'Connections',exact:true}).click();
 await page.locator('#add-connection').click();
 await page.getByLabel('Connection name',{exact:true}).fill('Review sandbox');
 await page.getByLabel('Connection string',{exact:true}).fill('Server=fake;Database=Demo;User Id=demo;Password=DO_NOT_STORE_123;');
 await page.getByRole('button',{name:'Add demo connection',exact:true}).click();
 check(await page.getByRole('heading',{name:'Review sandbox'}).isVisible(),'Added demo card');
 check(!await page.evaluate(()=>JSON.stringify(sessionStorage).includes('DO_NOT_STORE_123')),'Password must not be stored');
 await page.reload();
 check(await page.getByRole('heading',{name:'Review sandbox'}).isVisible(),'Connection label retained on reload');
 await page.getByRole('button',{name:'Remove',exact:true}).click();
 await page.getByRole('link',{name:'Database explorer',exact:true}).click();
 await page.locator('[data-object="dbo.Products"]').click();
 check(await page.locator('#object-details').innerText().then(s=>s.includes('Sku')),'Products columns');
 await page.locator('#explorer-connection').selectOption('stage');
 check(!await page.locator('#object-details').innerText().then(s=>s.includes('Sku')),'Staging omits Sku');
 await page.getByRole('link',{name:'Script table',exact:true}).click();
 const schema=await page.locator('#sql-output').innerText();
 check(schema.includes('CREATE TABLE [dbo].[Products]'),'Explorer to script selection');
 check(!schema.includes('[Sku]'),'Script uses selected staging connection');
 const schemaDownload=page.waitForEvent('download');await page.locator('#download-sql').click();
 check((await schemaDownload).suggestedFilename()==='commerce-schema.sql','Schema .sql download');
 await page.locator('[name=script-table]:checked').uncheck();
 await page.locator('#generate-schema').click();
 check(await page.locator('#download-sql').isDisabled(),'Empty selection disables download');
 await page.getByRole('link',{name:'INSERT generator',exact:true}).click();
 const sql=await page.locator('#sql-output').innerText();
 check(sql.includes("N'Sam O''Brien'")&&sql.includes("N'سارة أحمد'")&&sql.includes('NULL'),'SQL escaping, Unicode and NULL');
 check((sql.match(/INSERT INTO/g)||[]).length===7,'Seven inserts');
 const insertDownload=page.waitForEvent('download');await page.locator('#download-sql').click();
 check((await insertDownload).suggestedFilename()==='customers-inserts.sql','INSERT .sql download');
 await page.locator('#sample-query').selectOption('active');await page.locator('#generate-inserts').click();
 check((await page.locator('#sql-output').innerText()).match(/INSERT INTO/g).length===5,'Active filter');
 await page.locator('#query').fill('DELETE FROM dbo.Customers;');await page.locator('#generate-inserts').click();
 check(await page.locator('#query-error').innerText().then(s=>s.includes('sample SELECT')),'Unsupported query feedback');
 check(await page.locator('#download-sql').isDisabled(),'Invalid query clears stale output');
 await page.locator('#sample-query').selectOption('all');await page.locator('#destination').fill('dbo.Bad; DROP TABLE x');await page.locator('#generate-inserts').click();
 check(await page.locator('#query-error').innerText().then(s=>s.includes('schema.Table')),'Destination validation');
 await page.setViewportSize({width:390,height:844});
 for(const tool of ['schema','data','connections','explorer','scripts','inserts']) {
  await page.goto('http://localhost:5180/?demo=true&tool='+tool);
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),tool+' has page-level mobile overflow');
 }
 await page.screenshot({path:'preview-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.goto('http://localhost:5180/?demo=true');
 await page.screenshot({path:'preview-desktop.png',fullPage:true});
 check(!errors.length,'Browser errors: '+errors.join('; '));
 return 'PASS: schema modes/scope, data keys/ignore, connection lifecycle, explorer, SQL downloads, query validation, six mobile pages, no browser errors.';
}

